#!/bin/bash
set -e

ID="$1"
CONF="/etc/boxproxy/instances/${ID}.conf"
OUT="/etc/boxproxy/dante/${ID}.conf"

[ -f "$CONF" ] || exit 1
. "$CONF"

cat > "$OUT" <<EOF
logoutput: syslog

internal: 10.10.10.1 port = ${SOCKS_PORT}
external: ${PPP_IF}

socksmethod: username

user.privileged: root
user.notprivileged: nobody
user.libwrap: nobody

client pass {
    from: 10.10.10.0/24 to: 0.0.0.0/0
    log: connect disconnect error
}

socks pass {
    from: 10.10.10.0/24 to: 0.0.0.0/0
    command: connect udpassociate
    socksmethod: username
    log: connect disconnect error
}

socks pass {
    from: 0.0.0.0/0 to: 0.0.0.0/0
    command: udpreply
    log: connect disconnect error
}
EOF

chmod 600 "$OUT"
