#!/bin/sh

IFACE="$1"

for CONF in /etc/boxproxy/instances/*.conf; do
    [ -f "$CONF" ] || continue

    . "$CONF"

    if [ "$PPP_IF" = "$IFACE" ]; then
        ID=$(basename "$CONF" .conf)

        /bin/systemctl stop "boxproxy-dante@${ID}.service" >/dev/null 2>&1 || true
        /bin/systemctl stop "boxproxy-squid@${ID}.service" >/dev/null 2>&1 || true

        exit 0
    fi
done

exit 0
