#!/bin/sh

IFACE="$1"

for CONF in /etc/boxproxy/instances/*.conf; do
    [ -f "$CONF" ] || continue

    . "$CONF"

    if [ "$PPP_IF" = "$IFACE" ]; then
        ID=$(basename "$CONF" .conf)

        /usr/local/lib/boxproxy/squid-generate "$ID" || exit 1

        /bin/systemctl try-restart "boxproxy-squid@${ID}.service" >/dev/null 2>&1 || true

        exit 0
    fi
done

exit 0
