#!/bin/sh

IFACE="$1"

for CONF in /etc/boxproxy/instances/*.conf; do
    [ -f "$CONF" ] || continue

    . "$CONF"

    if [ "$PPP_IF" = "$IFACE" ]; then
        if [ -f /etc/ppp/resolv.conf ]; then
            DNS_SERVERS=$(awk '/^nameserver/ {printf "%s ", $2}' /etc/ppp/resolv.conf)

            if [ -n "$DNS_SERVERS" ]; then
                /usr/bin/resolvectl dns "$IFACE" $DNS_SERVERS
                /usr/bin/resolvectl domain "$IFACE" '~.'
            fi
        fi

        exit 0
    fi
done

exit 0
